### ISSUE TITLE
Keep our reducers DRY and more readable

### ISSUE THREAD

**Issue by DonRai** [optimaxdev/handbook#8]
Чтобы наши редьюсеры соблюдали принципы [DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself) и были более читаемы, предлагаю начать использоваться [type-to-reducer](https://github.com/tomatau/type-to-reducer) ([486B gzip](https://bundlephobia.com/result?p=type-to-reducer@1.1.0)).

Как выглядит наш типичный редьюсер
```javascript
export const orderReviewItems = (
    state: OrderReviewType = initialState,
    action: ActionType<OrderReviewType>,
): OrderReviewType => {
    switch (action.type) {
        case `${CHECKOUT.GET_ORDER_REVIEW_ITEMS}_FULFILLED`:
            return {...state, list: action.payload.data, status: 'fulfilled'};
        case `${CHECKOUT.GET_ORDER_REVIEW_ITEMS}_PENDING`:
            return {...state, selected: action.meta, status: 'pending'};
        default:
            return state;
    }
};
```

Как будет выглядеть с type-to-reducer
```javascript
export const orderReviewItems = typeToReducer(
    {
        [CHECKOUT.GET_ORDER_REVIEW_ITEMS]: {
            PENDING: (state, action) => ({
                ...initialState,
                ...state,
                selected: action.meta,
                status: 'pending',
            }),
            FULFILLED: (state, action) => ({
                ...state,
                list: action.payload.data,
                status: 'fulfilled',
            }),
        },
    },
    initialState,
);
```

Есть еще интересный момент как это будет работать с нашим flow. По факту внутри него стоит для всех аргументов any. Т.е. по факту наш eslint и flow не будут ругаться на него. Посмотреть как устроена у него типизация можно [здесь](https://github.com/tomatau/type-to-reducer/blob/master/src/index.d.ts).

Полностью типизированный пример:
```javascript
export const orderReviewItems = typeToReducer(
    {
        [CHECKOUT.GET_ORDER_REVIEW_ITEMS]: {
            PENDING: (state: OrderReviewType, action: ActionType<>): OrderReviewType => ({
                ...initialState,
                ...state,
                selected: action.meta,
                status: 'pending',
            }),
            FULFILLED: (
                state: OrderReviewType,
                action: ActionType<{payload: {data: Array<OrderReviewItemsType>}}>,
            ): OrderReviewType => ({
                ...state,
                list: action.payload.data,
                status: 'fulfilled',
            }),
        },
    },
    initialState,
);
```

Хорошо бы пойти дальше и отказаться от status='fulfilled' или status='pending' и ввести isFulfilled, isPending, которые будут содержать true или false. Т.е. boolean.
Пример:
```javascript
export const initialState = {
    selected: '',
    list: [],
    isPending: false,
    isFulfilled: false,
};

export const orderReviewItems = typeToReducer(
    {
        [CHECKOUT.GET_ORDER_REVIEW_ITEMS]: {
            PENDING: (state: OrderReviewType, action: ActionType<>): OrderReviewType => ({
                ...initialState,
                selected: action.meta,
                isPending: true,
            }),
            FULFILLED: (state: OrderReviewType, action: ActionType<>): OrderReviewType => ({
                ...initialState,
                list: action.payload.data,
                isFulfilled: true,
            }),
        },
    },
    initialState,
);
```

Тесты фиксить не надо. Они остаются такими же и не ломаются.

**Полезные ссылки**
- [рекомендация от redux-promise-middleware ](https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/reducers.md#large-applications)
- [type-to-reducer](https://github.com/tomatau/type-to-reducer)
- [принцип DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself)

**Comment by SmirnovW** [comment]
@DonRai 
Ну это никак не относится к DRY, это просто сахар для редюсеров.
И мы можем это сделать и без type-to-reducer https://medium.com/front-end-hacking/redux-lets-refactor-our-higher-order-duck-e44b0110befc.
По поводу isFulfilled, isPending, в них нет смысла, нам нужен только isLoading.

**Comment by DonRai** [comment]
We will move to redux-actions
